import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { LikedPostsProvider } from "@/context/LikedPostsContext";
import { SavedPostsProvider } from "@/context/SavedPostsContext";
import { UserProvider } from "@/context/UserContext";
import { getUserFromServer } from "@/lib/auth";
import { NotificationProvider } from "@/context/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// MUST be async to use await
export default async function RootLayout({ children }) {
  const serverUser = await getUserFromServer(); // valid HERE

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UserProvider serverUser={serverUser}>
            <LikedPostsProvider>
              <NotificationProvider>
                <SavedPostsProvider>{children}</SavedPostsProvider>
              </NotificationProvider>
            </LikedPostsProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
