// ...existing code...
export const API = {
  BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  SOCKET_IO_URL: process.env.NEXT_PUBLIC_SOCKET_IO_URL,
  AUTH: {
    LOGIN: process.env.NEXT_PUBLIC_AUTH_LOGIN_ENDPOINT,
    SIGNUP: process.env.NEXT_PUBLIC_AUTH_SIGNUP_ENDPOINT,
    ME: process.env.NEXT_PUBLIC_AUTH_ME_ENDPOINT,
  },
  USER: {
    PROFILE: process.env.NEXT_PUBLIC_USER_PROFILE_ENDPOINT,
    DELETE: process.env.NEXT_PUBLIC_USER_DELETE_ENDPOINT,
    STATE: process.env.NEXT_PUBLIC_USER_STATE_ENDPOINT,
  },
  ADMIN: {
    PROFILE: process.env.NEXT_PUBLIC_ADMIN_PROFILE_ENDPOINT,
    USERS: process.env.NEXT_PUBLIC_ADMIN_USERS_ENDPOINT,
    BLOCK_USER: process.env.NEXT_PUBLIC_ADMIN_BLOCK_USER_ENDPOINT,
    UNBLOCK_USER: process.env.NEXT_PUBLIC_ADMIN_UNBLOCK_USER_ENDPOINT,
    CHANGE_PASSWORD: process.env.NEXT_PUBLIC_ADMIN_CHANGE_PASSWORD_ENDPOINT,
    DELETE_ACCOUNT: process.env.NEXT_PUBLIC_ADMIN_DELETE_ACCOUNT_ENDPOINT,
    UPLOAD_ARTWORK: process.env.NEXT_PUBLIC_ADMIN_UPLOAD_ARTWORK_ENDPOINT,
  },
  POSTS: {
    LIKE: process.env.NEXT_PUBLIC_POST_LIKE_ENDPOINT,
    SAVE: process.env.NEXT_PUBLIC_POST_SAVE_ENDPOINT,
  },
  ARTWORKS: {
    LIST: process.env.NEXT_PUBLIC_ARTWORKS_ENDPOINT,
    DELETE: process.env.NEXT_PUBLIC_ARTWORKS_DELETE_ENDPOINT,
  },
  LIKES: {
    LIST: process.env.NEXT_PUBLIC_LIKES_ENDPOINT,
    LIKE_POST: process.env.NEXT_PUBLIC_LIKE_POST_ENDPOINT,
    ADD_LIKE: process.env.NEXT_PUBLIC_ADD_LIKE_ENDPOINT,
  },
  SAVED: {
    LIST: process.env.NEXT_PUBLIC_SAVED_POSTS_ENDPOINT,
    SAVE_POST: process.env.NEXT_PUBLIC_SAVE_POST_ENDPOINT,
  },
  SEARCH: process.env.NEXT_PUBLIC_SEARCH_ENDPOINT,
  CONTACT: process.env.NEXT_PUBLIC_CONTACT_ENDPOINT,
  EMAIL: process.env.NEXT_PUBLIC_SEND_EMAIL_ENDPOINT,
  CHAT: {
    MESSAGES: process.env.NEXT_PUBLIC_CHAT_MESSAGES_ENDPOINT,
    MESSAGES_VIEWER: process.env.NEXT_PUBLIC_CHAT_MESSAGES_VIEWER_ENDPOINT,
  },
};
